name: 720pMP4-Flex3D-2.67M-300e
dataset:
    type: VideoDataset
    args:
        data_path: data/ready.mp4
        frame_interval: 4
        crop_size: (720, 1280)
dataloader:
    type: VideoDataLoader
    args:
        batch_size: 3
        shuffle: false
        num_workers: 0
model:
    type: HNeRVMae
    img_size: (720, 1280)
    frame_interval: 4
    embed_dim: 8
    embed_size: (9, 16)
    decode_dim: 92
    lower_kernel: 1
    upper_kernel: 5
    scales:
    - 5
    - 4
    - 2
    - 2
    reduce: 3
    lower_width: 6
optimizer:
    type: Adam
    args:
        learning_rate: 1e-3
        beta1: 0.9
        beta2: 0.99
lr_scheduler:
    type: CosineAnnealingLR
    args:
        step_size: 10000
        eta_min: 1e-6
trainer:
    type: Trainer
    resume: false
    epochs: 300
    save_dir: saved/
    save_period: 100
    verbosity: 1
    monitor: min val_loss
    early_stop: 10,
    visual_tool: wandb
    project: nerv3d
    api_key_file: ./configs/api/tuanlda78202
    entity: tuanlda78202
    name: ready720pMP4-Flex3D-2.67M-300e
eval:
    eval_only: false
    eval_freq: 10
    eval_fps: false
    quant_model_bit: 8
    quant_embed_bit: 6
    quant_axis: 0
    dump_images: false
    dump_videos: false
    encoder_file: ''
log:
    debug: false
    print-freq: 50
    weight: None
    overwrite: false
    outf: unify
    suffix: ''
