dataloader:
  type: build_data

  args:
    data_path: "../uvg/yacht.yuv"
    batch_size: 1
    frame_interval: 2                   

arch:
  type: NeRV3D

  args:    
    embed_dim: 32
    embed_size: [9, 16]
    decode_dim: 70

    lower_kernel: 1
    upper_kernel: 5
    scales: [5, 3, 2, 2, 2]
    reduce: 1.2
    lower_width: 12

    ckpt_path: "../uvg/pretrain_vit-b_k400_e1600.pth"

loss:
  type: loss_fn

  args:
    loss_type: "L1-SSIM"

psnr:
  type: psnr_batch
  args:

msssim:
  type: msssim_batch
  args:

optimizer:
  type: Adam

  args:  
    lr: 0.002
    betas: [0.9, 0.99]

  lr_encoder: 0.0005

lr_scheduler:
  type: OneCycleLR

  args:
    max_lr: [0.0005, 0.002, 0.002, 0.002] 
    total_steps: 90000

trainer:  
  epochs: 300
  valid_period: 100
  save_dir: saved/
  save_period: 100

  mode: "offline" 
  name: "yacht_3m"
  
  project: 3dnerv-cvpr24
  entity: tuanlda78202
  api_key_file: "./config/api/tuanlda78202"

compression:
  compress_dir: compression/3m/yacht/
  embedding_path: "compression/3m/yacht/compressed_embedding.ncc"
  raw_decoder_path: "compression/3m/yacht/raw_decoder.pt"
  stream_path: "compression/3m/yacht/compressed_decoder.nnc"
  compressed_decoder_path: "compression/3m/yacht/compressed_decoder_converted.pt"

  model_qp: -38
  embed_qp: -38