dataloader:
  type: build_data

  args:
    data_path: "../uvg/beauty.yuv"                       
    batch_size: 1 # 
    frame_interval: 2 # 

psnr:
  type: psnr_batch

  args:
    batch_size: 1 # 
    frame_interval: 2 # 

msssim:
  type: msssim_batch

  args:
    batch_size: 1 # 

arch:
  type: NeRV3D

  args:
    img_size: [1080, 1920] 
    frame_interval: 2 # 
    
    embed_dim: 8
    embed_size: [9, 16]
    decode_dim: 634

    lower_kernel: 1
    upper_kernel: 5
    scales: [5, 4, 3, 2]
    reduce: 3
    lower_width: 6

    ckpt_path: "data/vmae_sdg.pth"

loss:
  type: loss_fn

  args:
    loss_type: "L2"

optimizer:
  type: Adam

  args: 
    lr: 0.0005
    betas: [0.9, 0.99]

lr_scheduler:
  type: CosineAnnealingLR

  args:
    T_max: 90000
    eta_min: 0

trainer:
  resume: False 
  
  epochs: 300
  valid_period: 20
  save_dir: saved/
  save_period: 50

  visual_tool: wandb
  mode: "disabled"
  name: "debug"
  project: nerv3d
  entity: tuanlda78202
  api_key_file: "./config/api/tuanlda78202"

compression:
  compress_dir: compression/12M/beauty/
  embedding_path: "compression/12M/beauty/compressed_embedding.ncc"
  raw_decoder_path: "compression/12M/beauty/raw_decoder.pt"
  stream_path: "compression/12M/beauty/compressed_decoder.nnc"
  compressed_decoder_path: "compression/12M/beauty/compressed_decoder_converted.pt"

  model_qp: -38
  embed_qp: -38          